class PalavrasChaveRoles{
    constructor() {
        //ordenado 
        this.esportes = [
            "atletismo",
            "atividade física",
            "badminton",
            "badminton paralímpico",
            "bandy",
            "basquetebol",
            "beach tennis",
            "bodyboard",
            "bobsleigh",
            "boxe",
            "caminhada",
            "canoagem",
            "competição",
            "corrida",
            "curling",
            "desporto",
            "esgrima",
            "esgrima paralímpica",
            "esportes",
            "esportes aquáticos",
            "esportes coletivos",
            "esportes de combate",
            "esportes de força",
            "esportes de inverno",
            "esportes de precisão",
            "esportes de resistência",
            "esportes de velocidade",
            "esportes individuais",
            "esportes paralímpicos",
            "exercício",
            "esqui alpino",
            "esqui cross-country",
            "futebol",
            "futsal",
            "golfe",
            "ginástica",
            "halterofilismo",
            "halterofilismo olímpico",
            "halterofilismo paraolímpico",
            "handebol",
            "hipismo",
            "hóquei no gelo",
            "jiu-jitsu",
            "jogo",
            "judô",
            "judô paralímpico",
            "judô paraolímpico",
            "karatê",
            "luge",
            "maratona",
            "maratona aquática",
            "natação",
            "natação sincronizada",
            "natação",
            "natação sincronizada",
            "ondas",
            "patinação artística",
            "patinagem de velocidade",
            "pentatlo moderno",
            "polo aquático",
            "remo",
            "rugby",
            "saltos ornamentais",
            "saltos ornamentais sincronizados",
            "saudável",
            "skeleton",
            "snouboard",
            "sol",
            "sol branco",
            "sol brilhante",
            "sol dourado",
            "sol escaldante",
            "sol fraco",
            "solitário",
            "stand up paddle",
            "surfe",
            "taekwondo",
            "taekwondo paralímpico",
            "tênis",
            "tênis de mesa",
            "tênis de mesa paralímpico",
            "torneio",
            "triatlo",
            "vela",
            "vôlei de praia",
            "vôlei de quadra",
            "voleibol",
            "wrestling"
        ];
        
        //ordenado 
        this.praia = [
            "alegre",
            "areia",
            "areias amarelas",
            "areias azuis",
            "areias brancas",
            "areias cor-de-rosa",
            "areias douradas",
            "areias escuras",
            "areias finas",
            "areias grossas",
            "areias negras",
            "areias prateadas",
            "areias roxas",
            "areias verdes",
            "areias vermelhas",
            "areias úmidas",
            "areias claras",
            "areias quentes",
            "areias secas",
            "areias quentes",
            "banhista",
            "banhista",
            "caiçara",
            "casal",
            "casquinha de sorvete",
            "copo de água",
            "descansado",
            "descontraído",
            "divertido",
            "espreguiçadeira",
            "encantador",
            "família",
            "feliz",
            "guarda-sol",
            "grupo de amigos",
            "jornal",
            "livre",
            "livro",
            "mar",
            "mar agitado",
            "mar azul",
            "mar branco",
            "mar calmo",
            "mar preto",
            "mar rosa",
            "mar vermelho",
            "mar verde",
            "maravilhoso",
            "mágico",
            "meio ambiente",
            "oceano",
            "ondas",
            "ondas altas",
            "ondas baixas",
            "ondas compridas",
            "ondas curtas",
            "ondas fortes",
            "ondas perfeitas",
            "paradisíaco",
            "perfeito",
            "protetor solar",
            "prato de praia",
            "praia",
            "relaxado",
            "revista",
            "saudável",
            "sol",
            "sol branco",
            "sol brilhante",
            "sol dourado",
            "sol escaldante",
            "sol forte",
            "sol frio",
            "sol fraco",
            "solitário",
            "surfista",
            "sorvete",
            "saudável",
            "sorvete",
            "sol",
            "solitário",
            "toalha",
            "tranquilo",
            "turista",
            "óculos de sol"
        ];
        
        //ordenado
        this.jogos =[
            "adrenalina",
            "alegria",
            "amigos",
            "arte",
            "aventura",
            "calma",
            "casual",
            "competitividade",
            "cooperação",
            "criatividade",
            "descoberta",
            "diversão",
            "educação",
            "emoção",
            "entretenimento",
            "esporte",
            "família",
            "felicidade",
            "habilidades",
            "história",
            "imaginação",
            "inteligência",
            "interativo",
            "lazer",
            "leitura",
            "liderança",
            "mar",
            "musica",
            "natureza",
            "narrativa",
            "oportunidade",
            "paz",
            "perspicácia",
            "persistência",
            "português",
            "problemas",
            "reflexão",
            "relaxamento",
            "saúde",
            "socialização",
            "sucesso",
            "tecnologias",
            "talento",
            "teamwork",
            "tempo",
            "teoria",
            "trabalho",
            "valores",
            "vida",
            "visualização",
            "volta",
            "vontade",
            "workshop",
        ]

        //ordenado
        this.jogosOnline = [
            "amigos",
            "chat",
            "cliente",
            "competição",
            "comunidade",
            "comunicação",
            "cooperação",
            "desync",
            "diversão",
            "eSports",
            "família",
            "free-to-play",
            "gratis",
            "hardcore",
            "lag",
            "ligas",
            "live",
            "multiplayer",
            "negócios",
            "oportunidade",
            "ping",
            "plataforma",
            "português",
            "rede",
            "socialização",
            "streaming",
            "tendências",
            "torneios",
            "torcedores",
            "video",
            "voice chat",
            "web",
            "YouTube",
        ]

        //ordenado
        this.passeios = [
            "alegria",
            "amor",
            "aventura",
            "arte",
            "compras",
            "cachoeira",
            "cidade",
            "compras",
            "cultura",
            "descanso",
            "descoberta",
            "educação",
            "emoção",
            "evento",
            "esperança",
            "festa",
            "floresta",
            "gastronomia",
            "história",
            "lago",
            "lazer",
            "mar",
            "montanha",
            "música",
            "natureza",
            "passeio",
            "praia",
            "parque",
            "relaxamento",
            "rio",
            "saúde",
            "sol",
            "socialização",
            "sonho",
            "turismo",
            "viagem",
        ]

        //ordenado
        this.parques = [
            "alegria",
            "amor",
            "amigos",
            "animal",
            "árvore",
            "área de lazer",
            "área de recreação",
            "área de esportes",
            "área verde",
            "banco",
            "casal",
            "cachoeira",
            "campo de futebol",
            "campo de vôlei",
            "cidade",
            "conservacionista",
            "corrida",
            "crescimento",
            "cultura",
            "desenho",
            "diversão",
            "educação",
            "eco",
            "ecologista",
            "em família",
            "entretenimento",
            "esperança",
            "exercício",
            "família",
            "feliz",
            "floresta",
            "flor",
            "fonte",
            "harmonia",
            "história",
            "ilha",
            "inseto",
            "lago",
            "lazer",
            "liberdade",
            "lista",
            "mar",
            "música",
            "natureza",
            "natação",
            "oásis",
            "parque",
            "parque infantil",
            "paz",
            "pássaro",
            "pessoa",
            "piscina",
            "prainha",
            "praça",
            "quadra de esportes",
            "quadra de tênis",
            "quadra de vôlei",
            "respiração",
            "relaxamento",
            "rio",
            "saudável",
            "socialização",
            "sol",
            "sonho",
            "sustentabilidade",
            "tarde",
            "terceiro lugar",
            "toda a família",
            "turismo",
            "vida",
            "verde",
            "viajar",
        ]

        //ordenado
        this.leitura = [
            "afeto",
            "amor",
            "aprendizado",
            "arte",
            "autoconhecimento",
            "autoajuda",
            "bem-estar",
            "biografia",
            "conhecimento",
            "criatividade",
            "diversão",
            "economia",
            "educação",
            "experiência",
            "ficção",
            "felicidade",
            "filosofia",
            "história",
            "imaginação",
            "informação",
            "conhecimento",
            "livro",
            "leitura",
            "memória",
            "melhor",
            "momento",
            "paz",
            "poema",
            "papel",
            "política",
            "reflexão",
            "relaxamento",
            "religião",
            "romance",
            "socialização",
            "sonho",
            "texto",
            "tempo",
            "vida",
        ]

        //ordenado
        this.pescaAcampamento = [
            "acampamento",
            "água",
            "amor",
            "alegria",
            "aventura",
            "anzol",
            "barco",
            "barraca",
            "barraca",
            "carretilha",
            "cachoeira",
            "calma",
            "casal",
            "chapéu",
            "comida",
            "confraternização",
            "coração",
            "descanso",
            "diversão",
            "esperança",
            "felicidade",
            "filho",
            "fogo",
            "fogueira",
            "felicidade",
            "ilha",
            "imprevisibilidade",
            "inovação",
            "isonomia",
            "juntos",
            "lago",
            "leitura",
            "lindo",
            "mar",
            "mochila",
            "natureza",
            "namorada",
            "nosso",
            "objetivo",
            "ocasião",
            "emoção",
            "paz",
            "peixe",
            "pesca",
            "pessoas",
            "plano",
            "proteção",
            "paixão",
            "reflexão",
            "relaxamento",
            "respeito",
            "rio",
            "saco de dormir",
            "sorriso",
            "sustentabilidade",
            "socialização",
            "sol",
            "sonho",
            "tanque",
            "tentação",
            "tempo",
            "tranquilidade",
            "viajar",
        ]   
    }

    getPalavrasChave(palavraChave){
        let itemDoMeioDoArrayJogos = this.jogos[this.jogos.length/2];
        let itemDoMeioDoArrayEsportes = this.jogos[this.jogos.length/2];
        let itemDoMeioDoArrayPraia = this.jogos[this.jogos.length/2];
        let itemDoMeioDoArrayPescaAcampamento = this.jogos[this.jogos.length/2];
        let itemDoMeioDoArrayLeitura = this.jogos[this.jogos.length/2];
        let itemDoMeioDoArrayJogosOnline = this.jogos[this.jogos.length/2];
        let itemDoMeioDoArrayPasseios = this.jogos[this.jogos.length/2];

        if(itemDoMeioDoArray.startsWith(palavraChave[0])){

        }

    }
}

export default PalavrasChaveRoles;